#!/bin/bash

echo "🚀 开始部署到 Netlify..."
echo ""
echo "由于你的环境没有安装 npm，我们使用最简单的方式："
echo ""
echo "📋 手动部署步骤（只需 30 秒）："
echo ""
echo "1️⃣  浏览器打开：https://app.netlify.com/drop"
echo ""
echo "2️⃣  把这个文件拖拽到网页："
echo "    文件位置：/Users/jicaifeng/.codeflicker/workshop/index.html"
echo ""
echo "3️⃣  等待 10 秒，你会得到一个链接：https://xxxxx.netlify.app"
echo ""
echo "✅ 这个链接可以在微信直接访问！"
echo ""
echo "---"
echo ""
echo "💡 提示：我已经为你打开了 Netlify Drop 页面"
echo "    只需要把 index.html 文件拖进去就完成了！"
